"""Turning a results database into labelled examples for the router finetune.

The store says what each approach did on each query; the label rule says which
one should have been picked. This module joins the two into the (text, label)
pairs the classifier trains on - and, just as importantly, records where they
came from.

Two things here are easy to get wrong invisibly, so both are pinned:

- **The text** is built by `optillm_router.build_input_text` out of the system
  prompt the harness sends for that dataset's category. Training on anything
  else trains on text the serving plugin will never produce.
- **The split** is decided per query, from the query's identity and a recorded
  seed alone - *before* any two-stage filtering. Under two-stage sweeping a
  query is either a control sample or one the baseline failed, and if the split
  were drawn after that distinction it would correlate with it.

Provenance is the other half of the job. Metrics can be regenerated by
re-running; which rows a finetune actually saw cannot be reconstructed
afterwards, so `Provenance` travels with the built set and is logged as run
parameters.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import NamedTuple, Sequence

from router_lab.datasets import category_of
from router_lab.grading import system_prompt
from router_lab.labels import LABEL_RULE_VERSION, label_query
from router_lab.store import ResultsStore
from router_lab.training.optillm_router import (
    APPROACHES,
    INFERENCE_EFFORT,
    build_input_text,
    label_index,
)

TRAIN = "train"
VALIDATION = "validation"
TEST = "test"
SPLITS = (TRAIN, VALIDATION, TEST)

SPLIT_RATIOS = (0.7, 0.15, 0.15)
"""Train/validation/test shares. Approximate at small volumes - see `assign_split`."""


class Cell(NamedTuple):
    """One (run, dataset, model) sweep - how the store keys its results."""

    run_id: str
    dataset: str
    model: str


@dataclass(frozen=True)
class Example:
    """One query, as the classifier sees it."""

    query_id: str
    dataset: str
    text: str
    approach: str
    """The winning approach's name - the label, before indexing."""
    label: int
    """Its position in optillm's approach list, i.e. the head's output index."""
    split: str
    effort: float = INFERENCE_EFFORT


@dataclass(frozen=True)
class _Labelled:
    """One query's verdict, before it is known whether it can become an example."""

    winner: str
    text: str
    any_correct: bool
    complete: bool
    """Whether this query was run through every approach its cell used."""


@dataclass(frozen=True)
class Provenance:
    """Where a built set came from. Logged as run parameters, never inferred."""

    run_ids: list[str]
    models: list[str]
    """The served models whose results were read - not the filter that selected
    them. A database holding two models collapses to one example per query, so
    what was actually read has to be on the record."""
    dataset_counts: dict[str, int]
    n_examples: int
    n_queries: int
    """Distinct queries found, including any dropped."""
    n_dropped: int
    """Queries whose winner is outside optillm's label space."""
    n_unsolved: int
    """Kept examples where *no* approach was correct, so the label is the rule's
    baseline fallback rather than an approach that worked. Training signal from
    these is noise; how much of it there is decides whether that matters."""
    coverage_fraction: float
    """Share of distinct queries run through every approach their cell used."""
    split_seed: int
    split_ratios: tuple[float, float, float]
    split_counts: dict[str, int]
    label_rule_version: str
    fingerprint: str
    """Content hash over (dataset, query, split, label, text) - the set's identity."""

    def as_params(self) -> dict[str, str | int | float]:
        """Flat, primitive-valued parameters a tracker can record as-is."""
        return {
            "examples/run_ids": ",".join(self.run_ids),
            "examples/models": ",".join(self.models),
            "examples/dataset_counts": format_counts(self.dataset_counts),
            "examples/n_examples": self.n_examples,
            "examples/n_queries": self.n_queries,
            "examples/n_dropped": self.n_dropped,
            "examples/n_unsolved": self.n_unsolved,
            "examples/coverage_fraction": self.coverage_fraction,
            "examples/split_seed": self.split_seed,
            "examples/split_ratios": ",".join(str(r) for r in self.split_ratios),
            "examples/split_counts": format_counts(self.split_counts),
            "examples/label_rule_version": self.label_rule_version,
            "examples/fingerprint": self.fingerprint,
        }


@dataclass(frozen=True)
class ExampleSet:
    """Built examples plus the provenance that explains them."""

    examples: list[Example]
    provenance: Provenance

    def split(self, name: str) -> list[Example]:
        return [e for e in self.examples if e.split == name]

    def label_counts(self, split: str | None = None) -> dict[str, int]:
        """How many examples each approach won - the class imbalance, measured."""
        counts: dict[str, int] = {}
        for example in self.examples:
            if split is None or example.split == split:
                counts[example.approach] = counts.get(example.approach, 0) + 1
        return counts


def build_examples(
    store: ResultsStore,
    *,
    run_ids: Sequence[str] | None = None,
    model: str | None = None,
    datasets: Sequence[str] | None = None,
    seed: int = 0,
    split_ratios: tuple[float, float, float] = SPLIT_RATIOS,
) -> ExampleSet:
    """Every labelled query in the selected runs, split and fingerprinted.

    A query found in more than one cell - re-run in a later sweep, or run against
    a second model - keeps one example, the latest run's verdict, and one split.
    Which models were read is recorded in the provenance; scope a build to one
    with `model` when that collapse would hide something.
    """
    cells = _cells(store, run_ids=run_ids, model=model, datasets=datasets)

    labelled: dict[tuple[str, str], _Labelled] = {}
    for cell in cells:
        coverage = store.approach_coverage(
            run_id=cell.run_id, dataset=cell.dataset, model=cell.model
        )
        full_matrix = {a for approaches in coverage.values() for a in approaches}
        prompt = system_prompt(category_of(cell.dataset))
        for query_id, approaches in coverage.items():
            results = store.results_for_query(
                run_id=cell.run_id,
                dataset=cell.dataset,
                model=cell.model,
                query_id=query_id,
            )
            label = label_query(results)
            labelled[(cell.dataset, query_id)] = _Labelled(
                winner=label.winner,
                text=build_input_text(prompt, results[0].question),
                any_correct=label.any_correct,
                complete=set(approaches) == full_matrix,
            )

    examples = [
        Example(
            query_id=query_id,
            dataset=dataset,
            text=entry.text,
            approach=entry.winner,
            label=label_index(entry.winner),
            split=assign_split((dataset, query_id), seed=seed, ratios=split_ratios),
        )
        for (dataset, query_id), entry in sorted(labelled.items())
        if entry.winner in APPROACHES
    ]

    dataset_counts: dict[str, int] = {}
    split_counts = {name: 0 for name in SPLITS}
    for example in examples:
        dataset_counts[example.dataset] = dataset_counts.get(example.dataset, 0) + 1
        split_counts[example.split] += 1
    kept = {(e.dataset, e.query_id) for e in examples}

    provenance = Provenance(
        run_ids=sorted({cell.run_id for cell in cells}),
        models=sorted({cell.model for cell in cells}),
        dataset_counts=dataset_counts,
        n_examples=len(examples),
        n_queries=len(labelled),
        n_dropped=len(labelled) - len(examples),
        n_unsolved=sum(
            not entry.any_correct for key, entry in labelled.items() if key in kept
        ),
        coverage_fraction=(
            sum(entry.complete for entry in labelled.values()) / len(labelled)
            if labelled
            else 0.0
        ),
        split_seed=seed,
        split_ratios=split_ratios,
        split_counts=split_counts,
        label_rule_version=LABEL_RULE_VERSION,
        fingerprint=fingerprint(examples),
    )
    return ExampleSet(examples=examples, provenance=provenance)


def assign_split(
    key: tuple[str, str],
    *,
    seed: int,
    ratios: tuple[float, float, float] = SPLIT_RATIOS,
) -> str:
    """Where one query lands, from its identity and the seed and nothing else.

    Hashing each query independently rather than shuffling and slicing the pool,
    because the pool grows: every new sweep adds queries, and a pooled shuffle
    would reassign the *existing* ones, moving a query out of the test split and
    into the training set of the next finetune. Leaking across successive
    experiments is worse than the cost, which is that the 70/15/15 shares are
    approximate at small volumes - so `split_counts` is recorded rather than
    assumed.
    """
    digest = hashlib.sha256(f"{seed}\t{key[0]}\t{key[1]}".encode()).digest()
    position = int.from_bytes(digest[:8], "big") / 2**64
    if position < ratios[0]:
        return TRAIN
    if position < ratios[0] + ratios[1]:
        return VALIDATION
    return TEST


def fingerprint(examples: Sequence[Example]) -> str:
    """A content hash over exactly what the model will be shown."""
    digest = hashlib.sha256()
    for example in examples:
        digest.update(
            f"{example.dataset}\t{example.query_id}\t{example.split}\t"
            f"{example.approach}\t{example.text}\n".encode()
        )
    return digest.hexdigest()


def _cells(
    store: ResultsStore,
    *,
    run_ids: Sequence[str] | None,
    model: str | None,
    datasets: Sequence[str] | None,
) -> list[Cell]:
    """The cells to read, oldest run first - so a later run's verdict wins.

    `list_runs` reports each run's datasets and models as sets, so their product
    can name cells that were never run; those come back empty and are skipped.
    """
    cells = []
    for run in store.list_runs():
        if run_ids is not None and run.run_id not in run_ids:
            continue
        for dataset in run.datasets:
            if datasets is not None and dataset not in datasets:
                continue
            for cell_model in run.models:
                if model is not None and cell_model != model:
                    continue
                if store.query_ids(
                    run_id=run.run_id, dataset=dataset, model=cell_model
                ):
                    cells.append(Cell(run.run_id, dataset, cell_model))
    return cells


def format_counts(counts: dict[str, int]) -> str:
    return ",".join(f"{key}={value}" for key, value in sorted(counts.items()))
